# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JP666
description: > # this means to ignore newlines until "baseurl:"
  Demo Slot OnLine Gacor Abis
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anonim1666.github.io" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
